Improve dependency management
RockefellerArchiveCenter/DACSspace pull request #29
Opened 2022-02-07 18:54 UTC by bonniegee

Adds a requirements.in file to track top level dependencies and a requirements.txt file generated by pip-compile. Also adds a dependabot config.

NOTE: This is branched off of `issue-15` so that needs to be merged first.

Fixes #20

2022-02-09 14:55 UTC, helrond reviewed
Wondering if we need some additional documentation in the README about dependencies and how to install. What do others think?

2022-02-11 16:04 UTC, a-berish approved these changes

2022-02-11 16:06 UTC, a-berish requested changes
I've added the README documentation as another issue (#33) so we can merge this.

2022-02-14 18:36 UTC, helrond approved these changes

2022-02-14 18:54 UTC, a-berish approved these changes
Moved the README documentation to a new issue #33 so we can merge this.

2022-02-14 18:54 UTC, kemartin2015 approved these changes

2022-02-14 18:55 UTC, daremiyo approved these changes

2022-02-14 19:09 UTC, merged