Linter and syntax formatter
RockefellerArchiveCenter/DACSspace pull request #32
Opened 2022-02-10 17:23 UTC by daremiyo

Fixes #18 
Adds pre-commit yaml file for automated listing. Also add documentation in ReadMe about pre-commit requirements

2022-02-10 17:28 UTC, bonniegee requested changes
This looks good! Two things:
* I wonder if there are any errors we want to ignore when running flake8 (such as line length). What do others think?
* Should we run the linter/do cleanup as part of this PR?

2022-02-10 18:12 UTC, daremiyo commented
> * Should we run the linter/do cleanup as part of this PR?

regarding running the linter, the code in this branch is still in Python2, so I thought we could first merge it into the base with the Python3 coding and then open a new issue and run the linter then

2022-02-10 19:57 UTC, helrond commented
I agree that it's probably a good idea to ignore certain flake8 error reports. The way to do that is in a config file, which you can read a bit more about [here](https://flake8.pycqa.org/en/latest/user/configuration.html). There is a `tox.ini` file that's part of #31 but it might make sense to add a `.flake8` file here so we don't get into too many merge conflicts.

2022-02-14 22:25 UTC, bonniegee approved these changes

2022-02-15 14:06 UTC, helrond approved these changes

2022-02-15 14:08 UTC, kemartin2015 approved these changes

2022-02-15 14:44 UTC, a-berish approved these changes

2022-02-15 17:06 UTC, merged