Adds validator class, fixes Issue 23
RockefellerArchiveCenter/DACSspace pull request #38
Opened 2022-03-10 16:26 UTC by a-berish

- Adds a validator class with a basic schema
- Adds unit testing for the validator class
- Adds fixtures (both invalid and valid resource JSON)

2022-03-10 17:29 UTC, helrond requested changes
A couple of pretty minor changes suggested below.

2022-03-10 17:29 UTC, helrond commented on dacsspace/validator.py
> +# Creates a simple schema to validate json against
If this comment is important to understanding the code, let's consider adding it to the docstring. Otherwise it should be removed.

2022-03-10 17:29 UTC, helrond commented on dacsspace/validator.py
> +# Checks data against schema
Same with this comment - if it's necessary for someone to understand the code then we should move it to the docstring. If not, it should be removed.

2022-03-10 17:29 UTC, helrond commented on dacsspace/validator.py
> +        # print(data)
Let's get rid of the commented lines here and below in lines 43, 45 and 50.

2022-03-10 17:29 UTC, helrond commented on tests/test_validator.py
> +        invalid_json = "fixtures/invalid_resource.json"
I would suggest renaming your fixture to give it a slightly more descriptive filename (like "missing title"). As our schema grows, we'll want to add more invalid resources to test that things are working as expected with different invalid cases.

2022-03-11 13:50 UTC, bonniegee approved these changes
+1 to Hillel's points about comments and docstrings--otherwise this is good to go!

2022-03-11 17:54 UTC, daremiyo approved these changes

2022-03-11 18:02 UTC, kemartin2015 approved these changes

2022-03-11 18:28 UTC, helrond approved these changes

2022-03-14 16:26 UTC, merged