fixes #73
RockefellerArchiveCenter/DACSspace pull request #76
Opened 2022-05-04 18:55 UTC by bonniegee

2022-05-05 17:01 UTC, a-berish approved these changes

2022-05-05 17:49 UTC, kemartin2015 approved these changes

2022-05-05 18:19 UTC, daremiyo approved these changes

2022-05-09 14:59 UTC, helrond requested changes
Does it make sense to add something about tests and linting here?

2022-05-11 15:58 UTC, a-berish approved these changes

2022-05-11 16:23 UTC, kemartin2015 approved these changes

2022-05-11 17:49 UTC, daremiyo approved these changes

2022-05-11 18:35 UTC, helrond approved these changes
Dig this!

2022-05-11 19:22 UTC, merged