Updates Usage section in Readme
RockefellerArchiveCenter/DACSspace pull request #77
Opened 2022-05-05 17:59 UTC by daremiyo

Fixes #72

2022-05-09 14:58 UTC, helrond requested changes

2022-05-09 14:58 UTC, helrond commented on README.md
> +Using the command line, navigate to the directory containing the DACSspace repository and run `dacsspace.py` to execute the script.
I *believe* you actually just need to run `dacsspace` BUT you also need to pass arguments.

2022-05-09 14:58 UTC, helrond commented on README.md
> +The DACSspace client will handle communication with your ArchivesSpace repository and gets the data from the resources in your AS repository. The client will only fetch data from published resources.
```suggestion
The DACSspace client will handle communication with your ArchivesSpace repository and gets the data from the resources in your AS repository. 
```

2022-05-09 14:58 UTC, helrond commented on README.md
> +The DACSspace client will handle communication with your ArchivesSpace repository and gets the data from the resources in your AS repository. The client will only fetch data from published resources.
We have an argument for this, right?

2022-05-09 14:58 UTC, helrond commented on README.md
>  ## Usage
General comment on this section - I wonder if it might be better to explain usage from the user's perspective, rather than explaining the internals of the library itself. I think there are basically two ways that the DACSspace library can be used:
- as a command-line utility (need to explain use cases, which arguments are necessary, etc)
- in another Python program (again, explain use cases, provide example)

2022-05-09 15:52 UTC, bonniegee requested changes
One small comment and +1 Hillel's suggestions

2022-05-09 15:52 UTC, bonniegee commented on README.md
> +DACSspace will check your ArchivesSpace and CSV filepaths. Your CSV filepath must have a .csv file extension and cannot contain the following characters: * ? : " < > | '
Might want to mention how these are supplied (config/command line)? Though that might be too much detail...

2022-05-11 18:34 UTC, helrond requested changes
I think the snippet needs to be update but otherwise this looks cool!

2022-05-11 18:34 UTC, helrond commented on README.md
> +
@daremiyo I think you need to update this with the edited snippet I sent you.

2022-05-11 21:00 UTC, helrond approved these changes

2022-05-12 13:32 UTC, kemartin2015 approved these changes

2022-05-12 14:16 UTC, bonniegee approved these changes

2022-05-12 16:21 UTC, a-berish approved these changes

2022-05-12 16:27 UTC, merged